repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: name-tests-test
      - id: pretty-format-json
      - id: no-commit-to-branch
        args: ['--branch', 'main']
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      # check type hinting
      - id: mypy
        files: ./app
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        description: Run ruff formatter
        entry: poetry run ruff format ./app
        language: system
        'types_or': [python, pyi]
        args: [--fix, --exit-non-zero-on-fix]
