repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: name-tests-test
      - id: pretty-format-json
      - id: no-commit-to-branch
        args: ['--branch', 'main']
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        description: Run mypy type hinting check
        language: system
        entry: mypy ./app
        args: [--disallow-untyped-defs]
        types: [python]
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        description: Run ruff formatter
        entry: ruff format ./app
        language: system
        args: [--exit-non-zero-on-fix]
        types: [python]
