name: On Push
on:
  push:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code  # clone repo to runner's file system
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
          poetry shell

      - name: Run tests with coverage coverage
        run: |
          coverage run -m pytest
          coverage report -m

      - name: Check coverage threshold
        run: |
          COVERAGE_THRESHOLD=80
          COVERAGE_PERCENTAGE=$(coverage report -m | grep -oP '\d+\%')
          if [ "${COVERAGE_PERCENTAGE%\%}" -lt "$COVERAGE_THRESHOLD" ]; then
            echo "Coverage is below threshold: $COVERAGE_PERCENTAGE, expected at least $COVERAGE_THRESHOLD"
            exit 1
          fi

      - name: Security scanning
        run: bandit -r ./app
        continue-on-error: true

      - name: Check bandit result
        run: |
          if [ $? -eq 0 ]; then
            echo "Bandit passed, no security issues found"
          else
            echo "Bandit failed, security issues found"
            exit 1
          fi
